article/urls.py
from django.urls import path, re_path
from . import views


app_name = 'article'
urlpatterns =[
        path('article-column', views.article_column,  name="article_column"),
        path('rename-column', views.rename_article_column, name="rename_article_column"),
        path('delete-column', views.delete_column, name="delete_column"),
        path('article-post', views.article_post, name="article_post"),
        path('article-list', views.article_list, name="article_list"),
        path('article-detail/<id>/<slug>/', views.article_detail, name="article_detail"),
        path('list-article-detail/<id>/<slug>/', views.list_article_detail, name="list_article_detail"),
        path('delete-article', views.delete_article, name="delete_article"),
        path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),
        path('article-titles', views.article_titles, name="article_titles"),
        path('author-article-titles/<username>/', views.article_titles, name="author_article_titles"),
        path('like-article', views.like_article, name="like_article"),
        
]

blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.blog_title, name="blog_title"),
    path("<article_id>/",views.blog_article),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog")),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace="article")),
    path('home/', TemplateView.as_view(template_name='home.html'), name="home"),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from slugify import slugify


# Create your models here.
class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.column
        
 
class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name="article", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name="article_column", on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User, related_name="article_like", blank=True)
    
    class Meta:
        ordering = ("title",)
        index_together = (('id', 'slug'),)
        
    def __str__(self):
        return self.title
        
    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)
        
    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id, self.slug])
        
    def get_url_path(self):
        return reverse("article:list_article_detail", args=[self.id, self.slug])


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, related_name="comments", on_delete=models.CASCADE)
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ("-created",)
        
    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column',)
        
        
class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body',)
        

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('commentator', 'body')

article/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from django.conf import settings

from .models import ArticleColumn, ArticlePost, Comment
from .forms import ArticleColumnForm, ArticlePostForm, CommentForm

import redis


r = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)


# Create your views here.
@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, 'article/column/article_column.html', 
                      {'columns': columns, 
                       'column_form': column_form
                      })
    if request.method == "POST":
        column_name = request.POST["column"]
        columns = ArticleColumn.objects.filter(user_id=request.user.id, 
                                               column=column_name)
        if columns:
            return HttpResponse("2")
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")


@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def delete_column(request):
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("0")
    
    
@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST['column_name']
    column_id = request.POST['column_id']
    columns = ArticleColumn.objects.filter(user_id=request.user.id, 
                                           column=column_name)
    if columns:
        return HttpResponse("2")
    else:
        try:
            line = ArticleColumn.objects.get(id=column_id)
            line.column = column_name
            line.save()
            return HttpResponse("1")
        except:
            return HttpResponse("0")
    
    
@login_required(login_url='/account/login/')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        return render(request, "article/column/article_post.html", 
                      {"article_post_form": article_post_form,
                       "article_columns": article_columns})


@login_required(login_url='/account/login/')
def article_list(request):
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 10)  # 规定每页最多4个
    page = request.GET.get("page")
    total_page = range(1, paginator.num_pages+1)
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    
    return render(request, "article/column/article_list.html", 
                    {"articles":articles, 
                     "page":current_page,
                     "total_page":total_page})
    
    
@login_required(login_url='/account/login/')
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article":article})


def list_article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    total_views = r.incr("article:{}:views".format(article.id))
    r.zincrby('article_ranking', value=article.id, amount=1)
    
    article_ranking = r.zrange('article_ranking', 0, -1,desc=True)[:10]
    article_ranking_ids = [int(id) for id in article_ranking]
    most_viewed = list(ArticlePost.objects.filter(id__in=article_ranking_ids))
    most_viewed.sort(key=lambda x: article_ranking_ids.index(x.id))
    
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article
            new_comment.save()
    else:
        comment_form = CommentForm()
            
    return render(request, "article/list/list_article_detail.html", 
                    {"article":article,
                     "total_views":total_views,
                     "most_viewed":most_viewed,
                     "comment_form":comment_form})


                
@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def delete_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")
        
        
@login_required(login_url='/account/login/')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title": article.title})
        this_article_column = article.column
        print(this_article_column)
        return render(request, "article/column/redit_article.html",
                      {
                        "article": article,
                        "article_columns": article_columns,
                        "this_article_column": this_article_column,
                        "this_article_form": this_article_form
                        
                      })
    if request.method == "POST":
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST["column_id"])
            redit_article.title = request.POST["title"]
            redit_article.body = request.POST["body"]
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")
            

def article_titles(request, username=None):
    if username:
        user = User.objects.get(username=username)
        article_titles =ArticlePost.objects.filter(author=user)
        try:
            userinfo = user.userinfo
        except:
            userinfo = None
    else:
        article_titles = ArticlePost.objects.all()
        userinfo = None
    paginator = Paginator(article_titles, 10)
    page = request.GET.get('page')
    total_page = range(1, paginator.num_pages+1)
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, "article/column/article_titles.html",                      
                    {"articles":articles, 
                     "page":current_page, 
                     "total_page":total_page, 
                     "userinfo":userinfo
                    })


@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def like_article(request):
    article_id = request.POST.get("id")
    action = request.POST.get("action")
    if article_id and action:
        try:
            article = ArticlePost.objects.get(id=article_id)
            if action == "like":
                article.users_like.add(request.user)
                return HttpResponse("1")
            else:
                article.users_like.remove(request.user)
                return HttpResponse("2")
        except:
            return HttpResponse("no")
            

templates/article/list/article_titles.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}article titles{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>学习一时爽，一直学习一直爽</h1>
    
</div>
<hr>
<div class="container"> 
    {% for article in articles %}
        <div class="list-group">
            <a href="{{ article.get_url_path }}" class="list-group-item">
            <h4 class="list-group-item-heading active" >{{ article.title }}</h4>
            
            <p class="list-group-item-text">作者：
                
                    {{ article.author.username }}
                
            </p>
            
            <p class="list-group-item-text">日期：{{ article.created }}</p>
            <p class="list-group-item-text">栏目：{{ article.column }}</p>
            <p class="list-group-item-text">概要：{{ article.body|slice:'70'|linebreaks }}</p>
            </a>
        </div>
    {% endfor %}
    {% include "paginator.html" %}
</div>


<script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static '/js/layer.js' %}"></script>

<script type="text/javascript">
    function delete_article(the, article_id){
        var article_name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除文章",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除《'+article_name+'》</p></div>',
            btn: ['确定','取消'],
            yes: function(){
                $.ajax({
                    url: '{% url "article:delete_article" %}',
                    type: 'POST',
                    data: {"article_id": article_id},
                    success: function(e){
                        if (e == '1'){
                            parent.location.reload();
                            layer.msg("删除成功");
                        } else {
                            parent.location.reload();
                            layer.msg("文章删除失败")
                        }
                    },
                });
            },
            btn2: function(index, layero){
                layer.close(index);
            },
        });
    };
</script> 
{% endblock %}

templates/article/list/latest_articles.html
<ul>
    {% for article in latest_articles %}
    <li>
        <a href="{{ article.get_url_path }}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>

templates/article/list/list_article_detail.html
{% extends "base.html" %}

{% load staticfiles %}
{% load article_tags %}
{% block title %}article detail{% endblock %}

{% block content %}

{% with total_likes=article.users_like.count users_like=article.users_like.all %}
<div class="container">
    <div class="col-md-9">
        <header>
            <h1>{{ article.title }}</h1>
            <p>
                <a href="{% url 'article:author_article_titles' article.author.username %}">
                    {{ article.author.username }}
                </a>  |  {{ article.created }}  |  {{ article.column }}  |
                <span id="like_area" class="glyphicon glyphicon-thumbs-up">
                    {{ total_likes }} like{{ total_likes | pluralize }}  |
                </span>
                <span id="view_area">
                    {{ total_views }} view{{ total_views | pluralize }}  |
                </span>
            </p>
        </header>
        
        <link rel="stylesheet" href="{% static '/editor/css/editormd.preview.css' %}"/>
        <div id="editormd-view">
            <textarea  style="display:none;">
    {{ article.body }}
            </textarea>
        </div>
        <div>
            <p class="text-center">
                <button class="btn btn-default btn-sm" 
                        name="like" onclick="like_article({{ article.id }}, 'like')">
                    <span class="glyphicon glyphicon-thumbs-up"></span>
                    like
                </button>
                |
                <button class="btn btn-default btn-sm" 
                        name="unlike" onclick="like_article({{ article.id }}, 'unlike')">
                    <span class="glyphicon glyphicon-thumbs-down"></span>
                    unlike
                </button>
            </p>
        </div>
        <div>
            <p class="text-center"><strong>点赞本文的读者</strong></p>
            {% for user in article.users_like.all %}
            <p class="text-center">{{ user.username }}</p>
            {% empty %}
            <p class="text-center">还没有人对本文表态</p>
            {% endfor %}
        </div>
        
        <hr>
        <div>
            <h3 style="margin-left:5px">
                <span class="glyphicon glyphicon-bullhorn"></span>
                本文有{{ article.comments.count }}条评论 
            </h3>
            {% for comment in article.comments.all %}
                <div>
                    <p><strong>{{ comment.commentator }}</strong>说：</p>
                    <p class="text-muted" style="margin-left:40px">{{ comment.created }}</p>
                    <p style="margin-left:40px">{{ comment.body }}</p>
                </div>
            {% empty %}
            <p style="margin-left:40px">还没有人评论</p>
            {% endfor %}
            
            <h3>
                <span class="glyphicon glyphicon-send"></span>
                只能夸我，批评一概不理
            </h3>
            <form class="form-horizontal" action="." role="form" method="post">{% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="inputEmail3">评论员</label>
                    <div class="col-sm-10">
                        {{ comment_form.commentator }}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="inputEmail3">评论</label>
                    <div class="col-sm-10">
                        {{ comment_form.body }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <p><input type="submit" name="" value="发表评论" class="btn btn-primary btn-sm"><p>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
    
    <div class="col-md-3">
        <p class="text-center"><h3>最受欢迎的文章</h3></p>
        <ol>
            {% for article_rank in most_viewed %}
            <li>
                <a href="{{ article_rank.get_url_path }}">{{ article_rank.title }}</a>
            </li>
            {% endfor %}
        </ol>
        <hr>
        <p class="text-center"><h3>最新发布的文章</h3></p>
        {% latest_articles 7 %}
        <hr>
        <p class="text-center"><h3>评论最多的文章</h3></p>
        {% most_commented_articles as most_comments %}
        <ol>
            {% for comment_article in most_comments %}
            <li>
                <a href="{{ comment_article.get_url_path }}">{{ comment_article.title }}</a>
            </li>
            {% endfor %}
        </ol>
    </div>
    
</div>


<script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/marked.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/prettify.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/raphael.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/underscore.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/sequence-diagram.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/flowchart.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/jquery.flowchart.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/editormd.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/layer.js' %}"></script>


<script type="text/javascript">
$(function(){
    editormd.markdownToHTML("editormd-view", {
        htmlDecode: "style, script, iframe",
        emoji: true,
        taskList: true,
        tex: true,
        flowChart: true,
        sequenceDiagram: true,
    });
});
function like_article(id, action){ 
    var likes = {{ total_likes }}
    $.ajax({
        url: "{% url 'article:like_article' %}",
        type: "POST",
        data: {"id":id, "action":action},
        success: function(e){
        // 就点个赞，还得把整个页面刷新下？太过分了
            if (e[0]=="1"){
                layer.msg("感谢点赞");
                window.location.reload();
            } else if (e[0]=="2") {
                layer.msg("我不写了！哼～");
                window.location.reload();
            };

            
        },
        
    });
    // alert(likes);
    // document.getElementById("like_area").innerHTML=" "+likes+" like {{ total_likes | pluralize }}";
}

</script>



{% endwith %}
{% endblock %}