article/urls.py
from django.urls import path, re_path
from . import views


app_name = 'article'
urlpatterns =[
        path('article-column', views.article_column,  name="article_column"),
        path('rename-column', views.rename_article_column, name="rename_article_column"),
        path('delete-column', views.delete_column, name="delete_column"),
        path('article-post', views.article_post, name="article_post"),
        path('article-list', views.article_list, name="article_list"),
        path('article-detail/<id>/<slug>/', views.article_detail, name="article_detail"),
        path('list-article-detail/<id>/<slug>/', views.list_article_detail, name="list_article_detail"),
        path('delete-article', views.delete_article, name="delete_article"),
        path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),
        path('article-titles', views.article_titles, name="article_titles"),
        path('author-article-titles/<username>/', views.article_titles, name="author_article_titles"),
        path('like-article', views.like_article, name="like_article"),
        
]

blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.blog_title, name="blog_title"),
    path("<article_id>/",views.blog_article),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog")),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace="article")),
    path('home/', TemplateView.as_view(template_name='home.html'), name="home"),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from slugify import slugify


# Create your models here.
class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.column
        
 
class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name="article", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name="article_column", on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User, related_name="article_like", blank=True)
    
    class Meta:
        ordering = ("title",)
        index_together = (('id', 'slug'),)
        
    def __str__(self):
        return self.title
        
    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)
        
    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id, self.slug])
        
    def get_url_path(self):
        return reverse("article:list_article_detail", args=[self.id, self.slug])


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, related_name="comments", on_delete=models.CASCADE)
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ("-created",)
        
    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

article/forms.py
from django import forms
from .models import ArticleColumn, ArticlePost, Comment


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column',)
        
        
class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body',)
        

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('commentator', 'body')

article/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from django.conf import settings

from .models import ArticleColumn, ArticlePost, Comment
from .forms import ArticleColumnForm, ArticlePostForm, CommentForm

import redis


r = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)


# Create your views here.
@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, 'article/column/article_column.html', 
                      {'columns': columns, 
                       'column_form': column_form
                      })
    if request.method == "POST":
        column_name = request.POST["column"]
        columns = ArticleColumn.objects.filter(user_id=request.user.id, 
                                               column=column_name)
        if columns:
            return HttpResponse("2")
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")


@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def delete_column(request):
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("0")
    
    
@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST['column_name']
    column_id = request.POST['column_id']
    columns = ArticleColumn.objects.filter(user_id=request.user.id, 
                                           column=column_name)
    if columns:
        return HttpResponse("2")
    else:
        try:
            line = ArticleColumn.objects.get(id=column_id)
            line.column = column_name
            line.save()
            return HttpResponse("1")
        except:
            return HttpResponse("0")
    
    
@login_required(login_url='/account/login/')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        return render(request, "article/column/article_post.html", 
                      {"article_post_form": article_post_form,
                       "article_columns": article_columns})


@login_required(login_url='/account/login/')
def article_list(request):
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 10)  # 规定每页最多4个
    page = request.GET.get("page")
    total_page = range(1, paginator.num_pages+1)
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    
    return render(request, "article/column/article_list.html", 
                    {"articles":articles, 
                     "page":current_page,
                     "total_page":total_page})
    
    
@login_required(login_url='/account/login/')
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article":article})


def list_article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    total_views = r.incr("article:{}:views".format(article.id))
    r.zincrby('article_ranking', value=article.id, amount=1)
    
    article_ranking = r.zrange('article_ranking', 0, -1,desc=True)[:10]
    article_ranking_ids = [int(id) for id in article_ranking]
    most_viewed = list(ArticlePost.objects.filter(id__in=article_ranking_ids))
    most_viewed.sort(key=lambda x: article_ranking_ids.index(x.id))
    
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article
            new_comment.save()
    else:
        comment_form = CommentForm()
            
    return render(request, "article/list/list_article_detail.html", 
                    {"article":article,
                     "total_views":total_views,
                     "most_viewed":most_viewed,
                     "comment_form":comment_form})


                
@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def delete_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")
        
        
@login_required(login_url='/account/login/')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title": article.title})
        this_article_column = article.column
        print(this_article_column)
        return render(request, "article/column/redit_article.html",
                      {
                        "article": article,
                        "article_columns": article_columns,
                        "this_article_column": this_article_column,
                        "this_article_form": this_article_form
                        
                      })
    if request.method == "POST":
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST["column_id"])
            redit_article.title = request.POST["title"]
            redit_article.body = request.POST["body"]
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")
            

def article_titles(request, username=None):
    if username:
        user = User.objects.get(username=username)
        article_titles =ArticlePost.objects.filter(author=user)
        try:
            userinfo = user.userinfo
        except:
            userinfo = None
    else:
        article_titles = ArticlePost.objects.all()
        userinfo = None
    paginator = Paginator(article_titles, 10)
    page = request.GET.get('page')
    total_page = range(1, paginator.num_pages+1)
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, "article/column/article_titles.html",                      
                    {"articles":articles, 
                     "page":current_page, 
                     "total_page":total_page, 
                     "userinfo":userinfo
                    })


@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def like_article(request):
    article_id = request.POST.get("id")
    action = request.POST.get("action")
    if article_id and action:
        try:
            article = ArticlePost.objects.get(id=article_id)
            if action == "like":
                article.users_like.add(request.user)
                return HttpResponse("1")
            else:
                article.users_like.remove(request.user)
                return HttpResponse("2")
        except:
            return HttpResponse("no")
            

templates/article/column/add_col.html
<div class="text-center" style="margin-top:20px">
    <p>请输入新的栏目名称</p>
    <p>{{ column_form.column }}</p>
    <ul>
        <li>不能以"_"或数字开头</li>
        <li>区分大小写</li>
        <li>名字中可包含'_',大小写字母，数字</li>
    </ul>
</div>

templates/article/column/article_column.html
{% extends 'article/base.html' %}

{% load staticfiles %}

{% block title %}article{% endblock %}

{% block content %}
<div>
    <p class="text-right"><button class="btn btn-primary" id="add_column" onclick="add_column()" data-toggle="tooltip" data-placement="bottom" title="不能以“_”、空格或数字开头,区分大小写,名字中可包含'_',大小写字母，数字">add column</button></p>
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>栏目名称</td>
            <td>操作</td>
            
        </tr>
        {% for column in columns %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ column.column }}</td>
            <td>
                <a name="edit" href="javascript:" onclick="edit_column(this, {{ column.id }})">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a name="delete" href="javascript:" onclick="del_column(this, {{ column.id }})">
                    <span class="glyphicon glyphicon-trash" style="margin-left:20px"></span>
                </a>
            </td>
        </tr>
        {% empty %}
        <p>还没有设置栏目，太懒了。</p>
        {% endfor %}
    </table>
</div>


<script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static '/js/layer.js' %}"></script>

<script type="text/javascript">
function add_column(){
//'<div class="text-center" style="margin-top:20px"><p>请输入新的栏目名称</p><p>{{ column_form.column }}</p><ul><li>不能以"_"或数字开头</li><li>区分大小写</li><li>名字中可包含'_',大小写字母，数字</li></ul></div>'
    var index = layer.open({
        type: 1,
        skin: "layui-layer-rim",
        area: ["400px", "200px"],
        title: "新增栏目",
        content: '<div class="text-center" style="margin-top:20px"><p>请输入新的栏目名称</p><p>{{ column_form.column }}</p></div>',
        btn: ['确定','取消'],
        yes: function(index, layero){
            var re = /^[^_0-9][a-zA-Z]*[a-z|A-Z|0-9|_]*/;
            var result;
            
            column_name = $('#id_column').val();
            // 正则表达式判断column_name是否合法
            result = column_name.match(re);
            if ( result != null){
                $.ajax({
                url: '{% url "article:article_column" %}',
                type: 'POST',
                data: {"column": column_name},
                success: function(e){
                    if (e == '1'){
                        parent.location.reload();
                        layer.msg("good");
                    } else {
                        layer.msg("此栏目已经存在，请更换名称。")
                    }
                    
                },
            });
            } else {
                layer.msg("名称不合法，请更换名称。")
            }
            // alert(column_name);
            
        },
        btn2: function(index, layero){
            layer.close(index);
        },
        
        
    });
};
function edit_column(the, column_id){
    var name = $(the).parents("tr").children("td").eq(1).text();
    var index = layer.open({
        type: 1,
        skin: "layui-layer-rim",
        area: ["400px", "200px"],
        title: "编辑栏目",
        content: '<div class="text-center" style="margin-top:20px"><p>请编辑栏目名称</p><input type="text" id="new_name" value="'+name+'"></div>',
        btn: ['确定','取消'],
        yes: function(index, layero){
            var re = /^[^_0-9|^ ][a-zA-Z]*[a-z|A-Z|0-9|_]*/;
            var result;
            
            new_name = $('#new_name').val();
            // 正则表达式判断column_name是否合法
            result = new_name.match(re);
            if ( result != null){
                $.ajax({
                url: '{% url "article:rename_article_column" %}',
                type: 'POST',
                data: {"column_id": column_id, "column_name": new_name},
                success: function(e){
                    if (e == '1'){
                        parent.location.reload();
                        layer.msg("good");
                    } else if (e == '2') {
                        layer.msg("此栏目已经存在，请更换名称。")
                    } else {
                        layer.msg("栏目名称修改失败，请更换名称。")
                    }
                    
                },
            });
            } else {
                layer.msg("名称不合法，请更换名称。")
            }
            // alert(column_name);
            
        },
        btn2: function(index, layero){
            layer.close(index);
        },
        
        
    });
};
function del_column(the, column_id){
    var name = $(the).parents("tr").children("td").eq(1).text();
    var index = layer.open({
        type: 1,
        skin: "layui-layer-rim",
        area: ["400px", "200px"],
        title: "删除栏目",
        content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除'+name+'栏目</p></div>',
        btn: ['确定','取消'],
        yes: function(index, layero){
            $.ajax({
                url: '{% url "article:delete_column" %}',
                type: 'POST',
                data: {"column_id": column_id},
                success: function(e){
                    if (e == '1'){
                        parent.location.reload();
                        layer.msg("删除成功");
                    } else {
                        parent.location.reload();
                        layer.msg("栏目删除失败")
                    }
                    
                },
            });
            // alert(column_name);
            
        },
        btn2: function(index, layero){
            layer.close(index);
        },
        
        
    });
}
</script> 
{% endblock %}

templates/article/column/article_detail.html
{% extends "article/base.html" %}

{% load staticfiles %}

{% block title %}article detail{% endblock %}

{% block content %}
<div>
    <header>
        <h1>{{ article.title }}</h1>
        <p>{{ article.author.username }}  |  {{ article.created }}  |  {{ article.column }}</p>
    </header>
    
    <link rel="stylesheet" href="{% static '/editor/css/editormd.preview.css' %}"/>
    <div id="editormd-view">
        <textarea  style="display:none;">
{{ article.body }}
        </textarea>
    </div>
</div>



<script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/marked.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/prettify.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/raphael.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/underscore.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/sequence-diagram.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/flowchart.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/lib/jquery.flowchart.min.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/editormd.min.js' %}"></script>


<script type="text/javascript">
$(function(){
    editormd.markdownToHTML("editormd-view", {
        htmlDecode: "style, script, iframe",
        emoji: true,
        taskList: true,
        tex: true,
        flowChart: true,
        sequenceDiagram: true,
    });
});
</script>


{% endblock %}

templates/article/column/article_list.html
{% extends 'article/base.html' %}

{% load staticfiles %}

{% block title %}article list{% endblock %}

{% block content %}
<div>
    <!--<p class="text-right"><button class="btn btn-primary" id="add_column" onclick="add_column()" data-toggle="tooltip" data-placement="bottom" title="不能以“_”、空格或数字开头,区分大小写,名字中可包含'_',大小写字母，数字">add column</button></p>-->
    <table class="table table-hover">
        <tr>
            <td>序号</td>
            <td>标题</td>
            <td>栏目</td>
            <td>发布时间</td>
            <td>操作</td>  
        </tr>
        {% for article in articles %}
        <tr id={{ article.id }}>
            <td>{{ forloop.counter }}</td>
            <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td>
            <td>{{ article.column }}</td>
            <td>{{ article.created }}</td>
            <td>
                <a name="redit" href="{% url 'article:redit_article' article.id  %}">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a name="delete" href="javascript:" onclick="delete_article(this, {{ article.id }})">
                    <span class="glyphicon glyphicon-trash" style="margin-left:20px"></span>
                </a>
            </td>
        </tr>
        {% empty %}
        <p>还没有发布一篇文章，太懒了。</p>
        {% endfor %}
    </table>
    {% include "paginator.html" %}
</div>


<script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static '/js/layer.js' %}"></script>

<script type="text/javascript">
    function delete_article(the, article_id){
        var article_name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除文章",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除《'+article_name+'》</p></div>',
            btn: ['确定','取消'],
            yes: function(){
                $.ajax({
                    url: '{% url "article:delete_article" %}',
                    type: 'POST',
                    data: {"article_id": article_id},
                    success: function(e){
                        if (e == '1'){
                            parent.location.reload();
                            layer.msg("删除成功");
                        } else {
                            parent.location.reload();
                            layer.msg("文章删除失败")
                        }
                    },
                });
            },
            btn2: function(index, layero){
                layer.close(index);
            },
        });
    };
</script> 
{% endblock %}

templates/article/column/article_post.html
{% extends 'article/base.html' %}

{% load staticfiles %}

{% block title %}article post{% endblock %}
{% block link %}
<link rel="stylesheet" href="{% static '/editor/css/style.css' %}">
<link rel="stylesheet" href="{% static '/editor/css/editormd.css' %}">
{% endblock %}
{% block content %}
<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top:10px">
            <div class="col-md-1 text-right"><span>标题：</span></div>
            <div class="col-md-10 text-left">{{ article_post_form.title }}</div>
        </div>
        <div class="row" style="margin-top:10px">
            <div class="col-md-1 text-right"><span>栏目：</span></div>
            <div class="col-md-10 text-left">
                <select id="which_column">
                    {% for column in article_columns %}
                    <option value="{{ column.id }}">{{ column.column }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row" style="margin-top:10px">
            <div class="col-md-1 text-right"><span>内容：</span></div>
            <div class="col-md-10 text-left" id="editormd">
                <textarea style="display:none" id="id_body"></textarea>
            </div>
        </div>
        <div class="row text-center" style="margin-top:10px">
            <input type="button" class="btn btn-primary btn-sm" value="发 布" onclick="publish_article()">
        </div>
    </form>
</div>


<script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static '/js/layer.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/editormd.min.js' %}"></script>
<script type="text/javascript">
$(function() {
    var editor = editormd("editormd", {
        width: "100%",
        height: 640,
        syncScrolling: "single",
        path: "{% static '/editor/lib/'%}"
    });
});
function publish_article(){
    var title = $("#id_title").val();
    var column_id = $("#which_column").val();
    var body = $("#id_body").val();
    $.ajax({
        url: '{% url "article:article_post" %}',
        type: 'POST',
        data: {"column_id": column_id, "title":title, "body":body},
        success: function(e){
            if (e == '1'){
                layer.msg("successful");
                location.href = "{% url 'article:article_list' %}";
            } else if (e == "2"){
                parent.location.reload();
                layer.msg("sorry, save fail.")
            } else {
                parent.location.reload();
                layer.msg("title can not be None.")
            }
            
        },
    });
}
</script> 
{% endblock %}

templates/article/column/article_titles.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load article_tags %}
{% block title %}article titles{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>学习一时爽，一直学习一直爽</h1>
    {% if userinfo %}
        <p>作者共有{% author_total_articles user %}篇文章</p>
    {% else %}
        <p>这里有{% total_articles %}篇文章</p>
    {% endif %}
    
</div>
<div class="container"> 
    {% if userinfo %}
    <div class="col-md-8">
    {% endif %}
    {% for article in articles %}
        <div class="list-group">
            <a href="{{ article.get_url_path }}" class="list-group-item">
            <h4 class="list-group-item-heading active" >{{ article.title }}</h4>
            <hr>
            <p class="list-group-item-text">作者：
                    {{ article.author.username }}
            </p>
            <p class="list-group-item-text">日期：{{ article.created }}</p>
            <p class="list-group-item-text">栏目：{{ article.column }}</p>
            <p class="list-group-item-text">概要：{{ article.body|slice:'70'|linebreaks }}</p>
            </a>
        </div>
    {% endfor %}
    {% include "paginator.html" %}
    {% if userinfo %}
    </div>
    {% endif %}
    
    {% if userinfo %}
    <div class="col-md-4">
        <div>
            {% if userinfo.photo %}
            <!-- <img src="{% static '/images/me.jpg' %}" class="img-circle" id="my_photo" name="user_face"-->
           <img src="{{ userinfo.photo | striptags }}" class="img-circle" id="my_photo" name="user_face">
            {% else %}
            <img src="{% static '/images/me.jpg' %}" class="img-circle" id="my_photo" name="user_face">
            {% endif %}
     
        </div>
        <div class="" style="margin-top:20px">
            <p>username: {{ user.username }}</p>
            {% if userinfo %}
                <p>company: {{ userinfo.company }}</p>
                <p>aboutme:{{ userinfo.aboutme|slice:'30'|linebreaks }}...</p>
            {% else %}
                <p>这个作者太懒，什么都没剩下。。。</p>
            {% endif %}
     
        </div>
    </div>
    {% endif %}
    
</div>


<script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>

{% endblock %}

templates/article/column/redit_article.html
{% extends 'article/base.html' %}

{% load staticfiles %}

{% block title %}article post{% endblock %}
{% block link %}
<link rel="stylesheet" href="{% static '/editor/css/style.css' %}">
<link rel="stylesheet" href="{% static '/editor/css/editormd.css' %}">
{% endblock %}
{% block content %}
<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top:10px">
            <div class="col-md-1 text-right"><span>标题：</span></div>
            <div class="col-md-10 text-left">{{ this_article_form.title }}</div>
        </div>
        <div class="row" style="margin-top:10px">
            <div class="col-md-1 text-right"><span>栏目：</span></div>
            <div class="col-md-10 text-left">
                <select id="which_column">
                    {% for column in article_columns %}
                        {% if column == this_article_column %}
                            <option value="{{ column.id }}" selected="selected">
                                {{ this_article_column.column }}
                            </option>
                        {% else %}
                            <option value="{{ column.id }}">
                                {{ column.column }}
                            </option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row" style="margin-top:10px">
            <div class="col-md-1 text-right"><span>内容：</span></div>
            <div class="col-md-10 text-left" id="editormd">
                <textarea style="display:none" id="id_body">{{ article.body }}</textarea>
            </div>
        </div>
        <div class="row text-center" style="margin-top:10px">
            <input type="button" class="btn btn-primary btn-sm" value="发 布" onclick="redit_article()">
        </div>
    </form>
</div>


<script type="text/javascript" src="{% static '/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static '/js/layer.js' %}"></script>
<script type="text/javascript" src="{% static '/editor/editormd.min.js' %}"></script>
<script type="text/javascript">
$(function() {
    var editor = editormd("editormd", {
        width: "100%",
        height: 640,
        // syncScrolling: "single",
        path: "{% static '/editor/lib/'%}"
    });
});
function redit_article(){
    var title = $("#id_title").val();
    var column_id = $("#which_column").val();
    var body = $("#id_body").val();
    $.ajax({
        url: '{% url "article:redit_article" article.id %}',
        type: 'POST',
        data: {"column_id": column_id, "title":title, "body":body},
        success: function(e){
            if (e == '1'){
                layer.msg("successful");
                location.href = "{% url 'article:article_list' %}";
            } else {
                parent.location.reload();
                layer.msg("sorry, save fail.")
            }
            
        },
    });
}
</script> 
{% endblock %}