account/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


app_name = 'account'
urlpatterns =[
        # path('login/', views.user_login, name='user_login'),
        # path('login/', LoginView.as_view(), name='user_login'),
        path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='user_login'),
        path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
        # path('logout/', auth_views.logout_then_login(), name="user_logout"),
        path('register/', views.register, name='user_register'),
        # password change
        path('password-change/', auth_views.PasswordChangeView.as_view(
                template_name="account/password_change_form.html",
                success_url="/account/password-change-done/"
            ), name='password_change'),
        path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
                template_name="account/password_change_done.html"
            ), name='password_change_done'),
        # password reset
        path('password-reset/', auth_views.PasswordResetView.as_view(
                email_template_name = 'account/password_reset_email.html',
                template_name="account/password_reset_form.html",
                success_url="/account/password-reset-done/",
                subject_template_name = 'account/password_reset_subject.txt'
            ), name="password_reset"),
        path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
                template_name="account/password_reset_done.html",
            ), name="password_reset_done"),
        path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                template_name="account/password_reset_confirm.html",
                success_url="/account/password-reset-complete/"
            ), name="password_reset_confirm"),
        path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
                template_name="account/password_reset_complete.html",
            ), name="password_reset_complete"),
        # my information
        path('my-information/', views.myself, name="my_information"),
        # edit my information
        path('edit-my-information/', views.myself_edit, name='edit_my_information'),
        path('my-image', views.my_image,  name="my_image"),
        
]

article/urls.py
from django.urls import path, re_path
from . import views


app_name = 'article'
urlpatterns =[
        path('article-column', views.article_column,  name="article_column"),
        path('rename-column', views.rename_article_column, name="rename_article_column"),
        path('delete-column', views.delete_column, name="delete_column"),
        path('article-post', views.article_post, name="article_post"),
        path('article-list', views.article_list, name="article_list"),
        path('article-detail/<id>/<slug>/', views.article_detail, name="article_detail"),
        path('list-article-detail/<id>/<slug>/', views.list_article_detail, name="list_article_detail"),
        path('delete-article', views.delete_article, name="delete_article"),
        path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),
        path('article-titles', views.article_titles, name="article_titles"),
        path('author-article-titles/<username>/', views.article_titles, name="author_article_titles"),
        path('like-article', views.like_article, name="like_article"),
        
]

blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.blog_title, name="blog_title"),
    path("<article_id>/",views.blog_article),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog")),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace="article")),
    path('home/', TemplateView.as_view(template_name='home.html'), name="home"),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equix="x-UA-Compatible" content="IE=Edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
	{% include "header.html" %}
	<div class="container">
		{% block content %}{% endblock %}
	</div>
    	{% include "footer.html" %}
	{% block javascript %}{% endblock %}
</body>
</html>

templates/footer.html
<div class="container">
	<hr>
	<p class="text-center">copy right www.dkider.com</p>
</div>

templates/header.html
{% load staticfiles %}

<div class="container">
    <nav class="navbar navbar-default" role="navgation">
        <div class="navbar-header">
		<a class="navbar-brand" href="{% url 'blog:blog_title' %}">
			<img src="{% static '/images/logo2.jpg' %}" width="100px" height="30px">
		</a>
        </div>
	<div>
		<ul class="nav navbar-nav" role="navgation">
		    <li class=""><a href="{% url 'home' %}">HOME</a></li>
			<li class=""><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
			<li class=""><a href="{% url 'article:article_titles' %}">Articles</a></li>
		</ul>

		<ul class="nav navbar-nav navbar-right" style="margin-right:20px">
			{% if user.is_authenticated %}
			<li>
			<div class="dropdown" style="margin-top:8px">
			    <button class="btn btn-default dropdown-toggle" 
			        type="button" id="dropdownMenu" data-toggle="dropdown">
			        {{ user.username }}
			        <span class="caret"></span>
			    </button>
			    
			    <ul class="dropdown-menu">
			    <li><a href="{% url 'account:password_change' %}">Change password</a></li>
			    <li><a href="{% url 'account:password_reset' %}">Reset password</a></li>
			    <li><a href="{% url 'account:my_information' %}">Profile</a></li>
			    <li><a href="{% url 'account:edit_my_information' %}">Edit Profile</a></li>
			    <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
			    </ul>
			</div>
			</li>
			<li><a href="{% url 'account:user_logout'%}">Logout</a></li>
			{% else %}
			<li sytle="margin-right:20px"><a href="{% url 'account:user_login' %}">Login</a></li>
			<li class=""><a href="{% url 'account:user_register' %}">Sign up</a></li>
			{% endif %}
		</ul>
	</div>
    </nav>
</div>


<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Home page{% endblock %}
{% block content %}



<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox"  wdith="1140" height="726">
    <div class="item active">
      <img src="{% static '/images/t1.jpg' %}" alt="...">
      <div class="carousel-caption">
        <h1>WELCOME YOU</h1>
      </div>
    </div>
    <div class="item">
      <img src="{% static '/images/t2.jpg' %}" alt="...">
      <div class="carousel-caption">
        <h1>Life is short. You need Python.</h1>
      </div>
    </div>
    <div class="item">
      <img src="{% static '/images/t3.jpg' %}" alt="...">
      <div class="carousel-caption">
        <h2>Django makes it easier to build better Web apps more quickly and with less code.</h2>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


{% endblock %}

templates/paginator.html
<div class="row text-center">
    <nav aria-label="Page navigation">
          <ul class="pagination">
            
            {% if page.has_previous %}
            <li>
              <a href="?page={{ page.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            {% else %}
            <li class="disabled">
              <a class="disabled" href="" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            {% endif %}
            </li>
            {% for p in total_page %}
                {% if page.number == p %}
                <li class="active"><a href="?page={{ p }}">{{ p }}</a></li>
                {% else %}
                <li><a href="?page={{ p }}">{{ p }}</a></li>
                {% endif %}
            {% endfor %}

            
            {% if page.has_next %}
            <li>
              <a href="?page={{ page.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
            {% else %}
            <li class="disabled">
              <a  href="" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
            {% endif %}
            </li>
          </ul>
    </nav>
</div>